name: lumiereorganics_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: ">=2.12.0 <3.0.0"
# sdk: ">=2.2.1 <3.0.0"
dependencies:
  animate_do: ^2.1.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  code_fields: ^0.0.4
  connectivity_plus: ^3.0.6
#  connectivity_plus:
  cupertino_icons: ^1.0.4
  device_info_plus: ^2.1.0
  equatable: ^2.0.3
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_breadcrumb: ^1.0.1
  flutter_form_builder: ^7.1.1
  flutter_local_notifications: ^9.4.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  form_builder_image_picker: ^2.0.0
  google_maps_flutter: ^2.2.6
  graphql_flutter: ^5.1.1
  graphql: ^5.1.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.5.0
  material_design_icons_flutter: ^5.0.6595
#  myfatoorah_flutter: ^2.1.10
  objectid: ^2.1.0
  package_info: ^2.0.2
  path_provider: ^2.0.9
#  persistent_bottom_nav_bar: ^4.0.2
  printing: ^5.8.0
  razorpay_flutter: ^1.3.0
  share: ^2.0.4
  shared_preferences: ^2.0.13
  string_validator: ^0.3.0
  table_calendar: ^3.0.5
  url_launcher: ^6.1.0
  form_builder_validators: ^8.1.1
  permission_handler: ^9.2.0
  freezed_annotation: ^2.0.1
  places_service: ^0.1.2
  flutter_google_places_sdk: ^0.3.2+3
  flutter_typeahead: ^3.2.6
  google_place: ^0.4.7
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  animated_splash_screen: ^1.3.0
  geolocator: ^8.2.0
  geocoding: ^2.1.0
  vertical_scrollable_tabview: ^0.0.9
  percent_indicator: ^4.2.3
#  html: ^0.15.0
#  flutter_html: ^2.2.1
  app_settings: ^4.1.5
  location: ^4.3.0
  google_maps_place_picker_mb:
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_inappwebview: ^5.8.0
  collection: ^1.16.0
  extended_image: ^6.2.2
  timer_builder: ^2.0.0
  animated_text_kit: ^4.2.2
  events_emitter: ^0.5.2
  flutter_html: ^3.0.0-alpha.6
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.4
  easy_refresh: ^3.3.4
  http: ^0.13.5
  otp_autofill: ^3.0.2
  iconsax: ^0.0.8
  badges: ^3.1.1
  persistent_bottom_nav_bar: ^5.0.2
  dotted_border: ^2.1.0
  image_picker: ^0.8.9
  flutter_image_compress: ^2.0.0
  
#  sms_autofill: ^2.3.0

#  audioplayers: ^4.1.0
#  stacked_card_carousel:

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.4
  freezed: ^2.0.2
  flutter_expanded_tile: ^0.3.7
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/base_module/presentation/core/assets/fonts/Poppins-Regular.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/Poppins-Bold.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/Poppins-SemiBold.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/Poppins-Medium.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/Poppins-Light.ttf
    - family: GeneralSans
      fonts:
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-Bold.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-BoldItalic.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-ExtraLight.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-ExtraLightItalic.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-Italic.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-Light.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-LightItalic.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-Medium.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-MediumItalic.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-Regular.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-SemiBold.ttf
        - asset: lib/base_module/presentation/core/assets/fonts/GeneralSans-SemiBoldItalic.ttf
  assets:
    - lib/base_module/presentation/core/assets/lang/
    - lib/base_module/presentation/core/assets/images/
    - lib/base_module/presentation/core/assets/fonts/
    - lib/user_module/presentation/core/assets/images/
    - lib/user_module/presentation/core/assets/lang/
    - lib/catalogue_module/presentation/core/assets/lang/
    - lib/cart_wishlist_module/presentation/core/assets/lang/
    - lib/orders_module/presentation/core/assets/lang/
    - lib/payment_module/presentation/core/assets/lang/
    - lib/base_module/presentation/core/assets/cert/lets-encrypt-r3.pem

flutter_icons:
  ios: true
  android: true
  background_color_ios: "#ffffff"
  image_path_ios: "lib/base_module/presentation/core/assets/images/app_store.png"
  image_path_android: "lib/base_module/presentation/core/assets/images/play_store.png"
  adaptive_icon_background: "lib/base_module/presentation/core/assets/images/background.png"
  adaptive_icon_foreground: "lib/base_module/presentation/core/assets/images/play_store.png"
